index:
    path: '/'
    controller: 'Symfony\Bundle\FrameworkBundle\Controller\TemplateController'
    defaults:
        template:  'index.html.twig'

blog:
    path: '/blog'
    controller: 'Symfony\Bundle\FrameworkBundle\Controller\TemplateController'
    defaults:
        template:  'blog/chat.html.twig'

youtube:
    path: '/youtube'
    controller: 'Symfony\Bundle\FrameworkBundle\Controller\TemplateController'
    defaults:
        template:  'youtube/chat.html.twig'

wikipedia:
    path: '/wikipedia'
    controller: 'Symfony\Bundle\FrameworkBundle\Controller\TemplateController'
    defaults:
        template:  'wikipedia/chat.html.twig'
